# filtering yago objects
select ?z 
where { 
dbr:Selwyn_Lloyd dbo:primeMinister ?z  
minus {
filter regex(?z, "Alec_Douglas-Home")
}
}
;

# filtering predicates
select ?z 
where { 
dbr:Selwyn_Lloyd dbo:primeMinister ?z  
filter (?z not in (dbr:Alec_Douglas-Home))
}

select dbr:Selwyn_Lloyd ?y ?z 
where { 
dbr:Selwyn_Lloyd ?y ?z
FILTER (?y NOT IN (<http://www.w3.org/2000/01/rdf-schema#label>,
<http://www.w3.org/2002/07/owl#sameAs>,
<http://www.w3.org/2000/01/rdf-schema#comment>,
<http://dbpedia.org/ontology/abstract>,
<http://www.w3.org/2004/02/skos/core#broader>,
<http://www.w3.org/2004/02/skos/core#prefLabel>,
<http://purl.org/dc/terms/subject>,
<http://dbpedia.org/ontology/wikiPageRedirects>,
<http://dbpedia.org/ontology/wikiPageID>,
<http://dbpedia.org/ontology/wikiPageLength>,
<http://xmlns.com/foaf/0.1/homepage>,
<http://purl.org/linguistics/gold/hypernym>,
<http://www.w3.org/ns/prov#wasDerivedFrom>,
<http://dbpedia.org/ontology/wikiPageWikiLink>,
<http://dbpedia.org/property/wikiPageUsesTemplate>,
<http://dbpedia.org/ontology/wikiPageRevisionID>,
<http://dbpedia.org/ontology/wikiPageInterLanguageLink>,
<http://dbpedia.org/ontology/wikiPageExternalLink>,
<http://dbpedia.org/ontology/activeYearsEndDate>,
<http://dbpedia.org/ontology/activeYearsStartDate>,
<http://dbpedia.org/property/termStart>,
<http://dbpedia.org/property/termEnd>,
<http://dbpedia.org/property/title>,
<http://dbpedia.org/property/years>
))
MINUS{
FILTER regex(?z,"http://dbpedia.org/class/yago|http://www.wikidata.org/entity/")
}
}
LIMIT 300


